"""add cascade delete to api_keys.owner_user_id

Revision ID: d60ff33f445c
Revises: fb90407859e1
Create Date: 2025-12-06 05:18:53.688673

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d60ff33f445c"
down_revision: Union[str, Sequence[str], None] = "fb90407859e1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("api_keys_owner_user_id_fkey"), "api_keys", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "api_keys", "users", ["owner_user_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "api_keys", type_="foreignkey")
    op.create_foreign_key(
        op.f("api_keys_owner_user_id_fkey"),
        "api_keys",
        "users",
        ["owner_user_id"],
        ["id"],
    )
    # ### end Alembic commands ###
